### PR TITLE
Revert "ввPull-request for branch 3"

### PR DESCRIPTION
**Pull request by DzmitryHlinkin**
Reverts aleksandragerasimova/repository1#6

### CODE REVIEW

**Comment by DzmitryHlinkin** [comment]
3333

**Comment by DzmitryHlinkin** [comment]
333888

Posted from Leverice

**Comment by aleksandragerasimova** [comment]
image

**Comment by aleksandragerasimova** [comment]
### asdfgh

**Comment by aleksandragerasimova** [comment]
**zxcvgbhnm,**
_asdfghjk_

**Comment by aleksandragerasimova** [comment]
### asdfgh
asdfgh

**Comment by aleksandragerasimova** [comment]
> asdfghjk

**Comment by aleksandragerasimova** [comment]
`<script type="text/javascript">

 </script>

`

**Comment by aleksandragerasimova** [comment]
`<script type="text/javascript">

 </script>`

**Pull request closed without merging**
